### ISSUE TITLE
Audience behavior analytics heat map

### ISSUE THREAD

**Issue by elffiona** [cs130-w21/15#3]
## Epic
Description and User Benefits:
The audience behavior analytics heat map is the report generated on a single post by our platform that displays the data collected from audience behaviors. The heat map is constantly tracking and logging the mouse movement of the readers of the corresponding blog. 
The heat map provides information including:
- Separating the entire post into small hexagon regions 
- Red hexagons show the places where the readers spent the most time on
- Dark blue hexagons show the places where the reader did not care to move their mouse to
The heat map is aiming to assist our users with additional information to gain a better understanding of the readers' interest and learn about what to focus on in further posts.

User Action:
- The users should be able to view the audience behavior analytics heat map of each post.

## User Stories
- [ ] Analytics report viewing #5
- [ ] Search posts based on tags #10
- [ ] Author log in #11

**Comment by yifan6082870** [comment]
Done
